# Generated by Selenium IDE
import shelve

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestDemo():
    def setup_method(self, method):
        options = Options()
        options.debugger_address = "127.0.0.1:9222"
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()


    def test_demo(self):
        # self.driver.get("https://ceshiren.com/")
        # self.driver.find_element(By.ID,"menu_contacts").click()
        # cookies = [
        #     {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wwrtx.vid', 'path': '/', 'secure': False,
        #      'value': '1688850837788022'},
        #     {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.vst', 'path': '/', 'secure': False,
        #      'value': 'XtV4QSHTuDVQ7rJlMwRsRNFGH1DZ5pmMj_Okdl9nP0Ib0WUzUmhERrjkRYcK0xKIOl-3_WXuiOYCHUKG1_8a9dfxetwuSyVZFgxH9YxBa3JM8w1DJz31PB0p-GrkkE7yGJNFsGeomtHE2tlm32gnGr7cDV94uX6ApP13LitgRTCT3lSRD1ffoziQuZQyIJ72-r2ZuGY7vaQc36Hivx9bUPSyyOsWMl1F8ySY_FWPIIj-lUH2skFQ3ahZbyrAH8q7q6xTfxn5ye9HDZ0GYfDxdg'},
        #     {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wxpay.vid', 'path': '/', 'secure': False,
        #      'value': '1688850837788022'},
        #     {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wxpay.corpid', 'path': '/', 'secure': False,
        #      'value': '1970325016146124'},
        #     {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.sid', 'path': '/', 'secure': False,
        #      'value': '6EuJrdclWvhtRUoTQP1mGrVsxMK7STElZ_4kZFVW-de3sSB4NOVK-rQyB9cf4Uab'},
        #     {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'wwrtx.d2st', 'path': '/', 'secure': False,
        #      'value': 'a469091'},
        #     {'domain': '.work.weixin.qq.com', 'httpOnly': False, 'name': 'Hm_lpvt_9364e629af24cb52acc78b43e8c9f77d',
        #      'path': '/', 'secure': False, 'value': '1596350236'},
        #     {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.refid', 'path': '/', 'secure': False,
        #      'value': '2965154412235823'},
        #     {'domain': 'work.weixin.qq.com', 'expiry': 1596380393, 'httpOnly': True, 'name': 'ww_rtkey', 'path': '/',
        #      'secure': False, 'value': '5ldvqsp'},
        #     {'domain': '.qq.com', 'expiry': 1596436655, 'httpOnly': False, 'name': '_gid', 'path': '/', 'secure': False,
        #      'value': 'GA1.2.1805038331.1596272056'},
        #     {'domain': '.work.weixin.qq.com', 'expiry': 1627711446, 'httpOnly': False, 'name': 'wwrtx.c_gdpr',
        #      'path': '/', 'secure': False, 'value': '0'},
        #     {'domain': '.qq.com', 'expiry': 1659422255, 'httpOnly': False, 'name': '_ga', 'path': '/', 'secure': False,
        #      'value': 'GA1.2.421793716.1596088472'},
        #     {'domain': '.qq.com', 'expiry': 2147483647, 'httpOnly': False, 'name': 'RK', 'path': '/', 'secure': False,
        #      'value': 'vHrIa0DdYx'},
        #     {'domain': '.qq.com', 'expiry': 2147483645, 'httpOnly': False, 'name': 'ptcz', 'path': '/', 'secure': False,
        #      'value': '5354b39ad7a71f6c7f272d07333a9c4b93d94e3f10f7f2f4912a37b016f107ae'},
        #     {'domain': '.qq.com', 'expiry': 1873592224, 'httpOnly': False, 'name': 'pac_uid', 'path': '/',
        #      'secure': False, 'value': '0_5ce0bca37e05d'},
        #     {'domain': '.work.weixin.qq.com', 'expiry': 1598942257, 'httpOnly': False, 'name': 'wwrtx.i18n_lan',
        #      'path': '/', 'secure': False, 'value': 'zh-cn'},
        #     {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.ltype', 'path': '/', 'secure': False,
        #      'value': '1'}, {'domain': '.work.weixin.qq.com', 'expiry': 1627886235, 'httpOnly': False,
        #                      'name': 'Hm_lvt_9364e629af24cb52acc78b43e8c9f77d', 'path': '/', 'secure': False,
        #                      'value': '1596183169,1596184510,1596272056,1596350236'},
        #     {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.ref', 'path': '/', 'secure': False,
        #      'value': 'direct'},
        #     {'domain': '.qq.com', 'expiry': 2147385600, 'httpOnly': False, 'name': 'pgv_pvid', 'path': '/',
        #      'secure': False, 'value': '1213920659'},
        #     {'domain': '.qq.com', 'expiry': 1908150732, 'httpOnly': False, 'name': 'tvfe_boss_uuid', 'path': '/',
        #      'secure': False, 'value': '8412a03edb0852f0'},
        #     {'domain': '.qq.com', 'expiry': 1596350296, 'httpOnly': False, 'name': '_gat', 'path': '/', 'secure': False,
        #      'value': '1'},
        #     {'domain': '.qq.com', 'expiry': 2147385600, 'httpOnly': False, 'name': 'pgv_pvi', 'path': '/',
        #      'secure': False, 'value': '8950759424'}]

        #print(self.driver.get_cookies())
        self.driver.get("https://work.weixin.qq.com/wework_admin/frame")
        db = shelve.open("cookies") #shelve对数据库进行保存
        #db['cookie']=self.driver.get_cookies()  #获取到cookies放到数据库中
        cookies = db['cookie']  #剔除掉不符合的元素
        for cookie in cookies:
            if "expiry" in cookie.keys():
                cookie.pop("expiry")
            self.driver.add_cookie(cookie)
        self.driver.get("https://work.weixin.qq.com/wework_admin/frame")
        time.sleep(5)
        self.driver.find_element_by_id("menu_contacts").click()
        time.sleep(3)

